name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ master ]

jobs:
  build-package:
    name: "Build Package"
    runs-on: flyci-macos-14-m2
    strategy:
      fail-fast: false
      matrix:
        xcode:
        - '15.2' # Swift 5.9
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          xcode: ${{ matrix.xcode }}
      - name: Build Package
        run: bundle exec rake build:package:all


  build-example:
    name: "Build Example App"
    runs-on: flyci-macos-14-m2
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          xcode: '15.2' # Swift 5.9
      - name: Build Example
        run: bundle exec rake build:example:all

  test-package:
    name: "Test Package"
    runs-on: flyci-macos-14-m2
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          xcode: '15.2' # Swift 5.9
      - name: Test Package
        run: bundle exec rake test:package
      - name: Process test artifacts
        if: always()
        run: bundle exec rake test:process
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestArtifacts
          path: Tests/Artifacts

  swiftlint:
    name: "Lint Swift"
    runs-on: flyci-macos-14-m2
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Lint Swift
        run: bundle exec rake lint:swift
