name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ master ]

jobs:
  build-package:
    name: "Build Package"
    runs-on: flyci-macos-14-m2
    strategy:
      fail-fast: false
      matrix:
        xcode:
        - '15.2' # Swift 5.9
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          xcode: ${{ matrix.xcode }}
      - name: Build Package
        run: bundle exec rake build:package:all


  build-example:
    name: "Build Example App"
    runs-on: flyci-macos-14-m2
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          xcode: '15.2' # Swift 5.9
      - name: Build Example
        run: bundle exec rake build:example:all

  test-package:
    name: "Test Package"
    runs-on: flyci-macos-14-m2
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          xcode: '15.2' # Swift 5.9
      - name: Test Package
        run: bundle exec rake test:package
      - name: Process test artifacts
        if: always()
        run: bundle exec rake test:process
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestArtifacts
          path: Tests/Artifacts

  build-xcframework-minimum-supported-version:
    name: "Build XCFramework"
    runs-on: macos-13
    strategy:
      matrix:
        xcode:
          # XCFrameworks are forwards-compatible but not backwards-compatible.
          # The Xcode version we use for this job is that oldest Xcode version that
          # will be able to use these XCFrameworks and the lottie-spm package.
          # This should be the minimum Xcode version permitted by the App Store.
          # As of April 2023, this is Xcode 14.1: https://developer.apple.com/news/?id=jd9wcyov
          #  - TODO: Once this minimum supported Xcode version is 15.0 or later,
          #    we can use Xcode 15.2 here and remove the `build-xcframework-with-visionOS-support` job.
          #    Testing in https://github.com/airbnb/lottie-spm/pull/12 shows that Xcode 15.0 can
          #    use an XCFramework built by Xcode 15.2.
          - '14.1' # Swift 5.7.1
    steps:
      - uses: actions/checkout@v2
      - uses: apple-actions/import-codesign-certs@v2
        continue-on-error: true
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_BASE_64 }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
      - uses: ./.github/actions/setup
        with:
          xcode: ${{ matrix.xcode }}
      - name: Build XCFramework
        run: SKIP_VISION_OS=true bundle exec rake build:xcframework[Lottie-Xcode-${{ matrix.xcode }}]
      - name: Upload XCFramework
        uses: actions/upload-artifact@v2
        with:
          name: BuildProducts
          path: .build/archives

  swiftlint:
    name: "Lint Swift"
    runs-on: flyci-macos-14-m2
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Lint Swift
        run: bundle exec rake lint:swift
